server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
      
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.52.164.224/dbrec?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: dbrec
    password: dbrec123$
    hikari:
      pool-name: DatebookHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      connection-test-query: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
